name: mobile_ec
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  icons_plus: ^4.0.0
  card_swiper: ^3.0.0
  equatable: ^2.0.5
  retrofit: ^4.0.3
  get_it: ^7.6.0
  intl: ^0.18.1
  floor: ^1.4.2
  flutter_hooks: ^0.18.3
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svgs/
